apiVersion: v1
kind: Namespace
metadata:
  name: depi


---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: one-pod-one-deployment
  namespace: depi
spec:
  hard:
    pods: '1'
    count/deployments.apps: '1'


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: depi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.1
        ports:
        - containerPort: 80