apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  mysql-root-password: YWRtaW4= # echo -n admin | base64 [i chose admin for simplicity]


---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: mysql-root-password


# kubectl exec mysql-pod -it -- bash
# mysql -u root -p 
# password = admin
